import * as XLSX from "xlsx";

// ─── Balancete structure matching the CC-3 official model ───
interface BalanceteLine {
  conta: string;
  designacao: string;
  isGroup?: boolean;     // group/parent account (bold, no input)
  isSubAccount?: boolean; // sub-account (indented)
}

// Class 1 — Meios Fixos e Investimentos
const classe1: BalanceteLine[] = [
  { conta: "1", designacao: "Meios Fixos e Investimentos", isGroup: true },
  { conta: "11", designacao: "Imobilizações Corpóreas", isGroup: true },
  { conta: "111", designacao: "Terrenos e recursos naturais" },
  { conta: "1111", designacao: "Terrenos em bruto", isSubAccount: true },
  { conta: "1112", designacao: "Terrenos com arranjos", isSubAccount: true },
  { conta: "1113", designacao: "Subsolos", isSubAccount: true },
  { conta: "1114", designacao: "Terrenos com edifícios", isSubAccount: true },
  { conta: "112", designacao: "Edifícios e outras construções" },
  { conta: "1121", designacao: "Edifícios", isSubAccount: true },
  { conta: "1122", designacao: "Outras construções", isSubAccount: true },
  { conta: "1123", designacao: "Instalações", isSubAccount: true },
  { conta: "113", designacao: "Equipamento básico" },
  { conta: "1131", designacao: "Material industrial", isSubAccount: true },
  { conta: "1132", designacao: "Ferramentas industriais", isSubAccount: true },
  { conta: "1133", designacao: "Melhoramentos em equipamentos básicos", isSubAccount: true },
  { conta: "114", designacao: "Equipamento de carga e transporte" },
  { conta: "1141", designacao: "Veículos pesados", isSubAccount: true },
  { conta: "1142", designacao: "Veículos mistos e ligeiros", isSubAccount: true },
  { conta: "115", designacao: "Equipamento administrativo" },
  { conta: "1151", designacao: "Equipamento informático", isSubAccount: true },
  { conta: "1152", designacao: "Equipamento social", isSubAccount: true },
  { conta: "1153", designacao: "Mobiliário", isSubAccount: true },
  { conta: "1154", designacao: "Outros equipamentos administrativos", isSubAccount: true },
  { conta: "116", designacao: "Taras e vasilhame" },
  { conta: "1161", designacao: "Embalagens retornáveis", isSubAccount: true },
  { conta: "1162", designacao: "Outras taras e outras embalagens", isSubAccount: true },
  { conta: "119", designacao: "Outras imobilizações corpóreas" },
  { conta: "1191", designacao: "Outras inst. e máquinas de uso específico", isSubAccount: true },
  { conta: "1192", designacao: "Outras imobilizações", isSubAccount: true },
  { conta: "12", designacao: "Imobilizações Incorpóreas", isGroup: true },
  { conta: "121", designacao: "Trespasses" },
  { conta: "122", designacao: "Despesas de investigação e desenvolvimento" },
  { conta: "123", designacao: "Propriedade industrial e outros direitos e contratos" },
  { conta: "1231", designacao: "Licenças informáticas diversas", isSubAccount: true },
  { conta: "1232", designacao: "Propriedade industrial e outros", isSubAccount: true },
  { conta: "124", designacao: "Despesas de constituição" },
  { conta: "129", designacao: "Outras imobilizações incorpóreas" },
  { conta: "13", designacao: "Investimentos Financeiros", isGroup: true },
  { conta: "131", designacao: "Empresas subsidiárias" },
  { conta: "1311", designacao: "Partes de capital", isSubAccount: true },
  { conta: "1312", designacao: "Obrigações e outros títulos de participação", isSubAccount: true },
  { conta: "1313", designacao: "Empréstimos", isSubAccount: true },
  { conta: "1314", designacao: "Adiantamentos por conta", isSubAccount: true },
  { conta: "132", designacao: "Empresas associadas" },
  { conta: "1321", designacao: "Partes de capital", isSubAccount: true },
  { conta: "1322", designacao: "Obrigações e outros títulos de participação", isSubAccount: true },
  { conta: "1323", designacao: "Empréstimos", isSubAccount: true },
  { conta: "1324", designacao: "Adiantamentos por conta", isSubAccount: true },
  { conta: "133", designacao: "Outros investimentos financeiros" },
  { conta: "1331", designacao: "Investimentos em outras empresas", isSubAccount: true },
  { conta: "1332", designacao: "Investimentos em imóveis", isSubAccount: true },
  { conta: "1333", designacao: "Fundos", isSubAccount: true },
  { conta: "1334", designacao: "Outros investimentos financeiros", isSubAccount: true },
  { conta: "1335", designacao: "Adiantamentos por conta de investimentos financeiros", isSubAccount: true },
  { conta: "14", designacao: "Imobilizações em curso", isGroup: true },
  { conta: "141", designacao: "Obras em curso" },
  { conta: "147", designacao: "Adiantamentos por conta de imobilizações corpóreas" },
  { conta: "148", designacao: "Adiantamentos por conta de imobilizações incorpóreas" },
  { conta: "149", designacao: "Adiantamentos por conta de investimentos financeiros" },
  { conta: "18", designacao: "Amortizações Acumuladas", isGroup: true },
  { conta: "181", designacao: "Imobilizações corpóreas" },
  { conta: "1811", designacao: "Terrenos e recursos naturais", isSubAccount: true },
  { conta: "1812", designacao: "Edifícios e outras construções", isSubAccount: true },
  { conta: "1813", designacao: "Equipamento básico", isSubAccount: true },
  { conta: "1814", designacao: "Equipamento de carga e transporte", isSubAccount: true },
  { conta: "1815", designacao: "Equipamento administrativo", isSubAccount: true },
  { conta: "1816", designacao: "Taras e vasilhame", isSubAccount: true },
  { conta: "1819", designacao: "Outras imobilizações corpóreas", isSubAccount: true },
  { conta: "182", designacao: "Imobilizações incorpóreas" },
  { conta: "1821", designacao: "Trespasses", isSubAccount: true },
  { conta: "1822", designacao: "Despesas de investigação e desenvolvimento", isSubAccount: true },
  { conta: "1823", designacao: "Propriedade industrial e outros direitos e contratos", isSubAccount: true },
  { conta: "1824", designacao: "Despesas de constituição", isSubAccount: true },
  { conta: "1829", designacao: "Outras imobilizações incorpóreas", isSubAccount: true },
  { conta: "183", designacao: "Investimentos financeiros em imóveis" },
  { conta: "1831", designacao: "Terrenos e recursos naturais", isSubAccount: true },
  { conta: "1832", designacao: "Edifícios e outras construções", isSubAccount: true },
  { conta: "19", designacao: "Provisões para investimentos financeiros", isGroup: true },
  { conta: "191", designacao: "Empresas subsidiárias" },
  { conta: "192", designacao: "Empresas associadas" },
  { conta: "193", designacao: "Outras empresas" },
  { conta: "194", designacao: "Fundos" },
  { conta: "199", designacao: "Outros investimentos financeiros" },
];

// Class 2 — Existências
const classe2: BalanceteLine[] = [
  { conta: "2", designacao: "Existências", isGroup: true },
  { conta: "21", designacao: "Compras", isGroup: true },
  { conta: "211", designacao: "Matérias-primas, subsidiárias e de consumo" },
  { conta: "212", designacao: "Mercadorias" },
  { conta: "215", designacao: "Outros materiais" },
  { conta: "217", designacao: "Devoluções de compras" },
  { conta: "218", designacao: "Descontos e abatimentos em compras" },
  { conta: "22", designacao: "Matérias-primas, subsidiárias e de consumo", isGroup: true },
  { conta: "221", designacao: "Matérias-primas" },
  { conta: "222", designacao: "Matérias subsidiárias" },
  { conta: "223", designacao: "Materiais diversos" },
  { conta: "224", designacao: "Embalagens de consumo" },
  { conta: "225", designacao: "Outros materiais" },
  { conta: "23", designacao: "Produtos e trabalhos em curso", isGroup: true },
  { conta: "231", designacao: "Produtos em curso" },
  { conta: "232", designacao: "Trabalhos em curso" },
  { conta: "24", designacao: "Produtos acabados e intermédios", isGroup: true },
  { conta: "241", designacao: "Produtos acabados" },
  { conta: "242", designacao: "Produtos intermédios" },
  { conta: "249", designacao: "Em poder de terceiros" },
  { conta: "25", designacao: "Subprodutos, desperdícios, resíduos e refugos", isGroup: true },
  { conta: "251", designacao: "Subprodutos" },
  { conta: "252", designacao: "Desperdícios, resíduos e refugos" },
  { conta: "26", designacao: "Mercadorias", isGroup: true },
  { conta: "261", designacao: "Mercadorias 1" },
  { conta: "262", designacao: "Mercadorias 2" },
  { conta: "269", designacao: "Em poder de terceiros" },
  { conta: "27", designacao: "Matérias-primas, mercadorias e outros materiais em trânsito", isGroup: true },
  { conta: "271", designacao: "Matérias-primas" },
  { conta: "272", designacao: "Outros materiais" },
  { conta: "273", designacao: "Mercadorias" },
  { conta: "28", designacao: "Adiantamentos por conta de compras", isGroup: true },
  { conta: "281", designacao: "Matérias-primas e outros materiais" },
  { conta: "282", designacao: "Mercadorias" },
  { conta: "29", designacao: "Provisões para depreciação de existências", isGroup: true },
  { conta: "292", designacao: "Matérias-primas, subsidiárias e de consumo" },
  { conta: "293", designacao: "Produtos e trabalhos em curso" },
  { conta: "294", designacao: "Produtos acabados e intermédios" },
  { conta: "295", designacao: "Subprodutos, desperdícios, resíduos e refugos" },
  { conta: "296", designacao: "Mercadorias" },
];

// Class 3 — Terceiros
const classe3: BalanceteLine[] = [
  { conta: "3", designacao: "Terceiros", isGroup: true },
  { conta: "31", designacao: "Clientes", isGroup: true },
  { conta: "311", designacao: "Clientes - correntes" },
  { conta: "312", designacao: "Clientes - títulos a receber" },
  { conta: "313", designacao: "Clientes - títulos descontados" },
  { conta: "318", designacao: "Clientes de cobrança duvidosa" },
  { conta: "319", designacao: "Clientes - saldos credores" },
  { conta: "32", designacao: "Fornecedores", isGroup: true },
  { conta: "321", designacao: "Fornecedores - correntes" },
  { conta: "322", designacao: "Fornecedores - títulos a pagar" },
  { conta: "328", designacao: "Fornecedores - facturas em recepção e conferência" },
  { conta: "329", designacao: "Fornecedores - saldos devedores" },
  { conta: "33", designacao: "Empréstimos", isGroup: true },
  { conta: "331", designacao: "Empréstimos bancários" },
  { conta: "332", designacao: "Empréstimos por obrigações" },
  { conta: "333", designacao: "Empréstimos por títulos de participação" },
  { conta: "339", designacao: "Outros empréstimos obtidos" },
  { conta: "34", designacao: "Estado", isGroup: true },
  { conta: "341", designacao: "Impostos sobre os lucros" },
  { conta: "3411", designacao: "Retenções a recuperar", isSubAccount: true },
  { conta: "3412", designacao: "Retenções a pagar", isSubAccount: true },
  { conta: "342", designacao: "Imposto de produção e consumo" },
  { conta: "343", designacao: "Imposto de rendimento de trabalho" },
  { conta: "344", designacao: "Imposto de circulação" },
  { conta: "345", designacao: "IVA - Imposto sobre o valor acrescentado" },
  { conta: "3451", designacao: "IVA suportado", isSubAccount: true },
  { conta: "3452", designacao: "IVA dedutível", isSubAccount: true },
  { conta: "3453", designacao: "IVA liquidado", isSubAccount: true },
  { conta: "3454", designacao: "IVA regularizações", isSubAccount: true },
  { conta: "3455", designacao: "IVA apuramento", isSubAccount: true },
  { conta: "3456", designacao: "IVA a pagar", isSubAccount: true },
  { conta: "3457", designacao: "IVA a recuperar", isSubAccount: true },
  { conta: "3458", designacao: "Reembolsos pedidos", isSubAccount: true },
  { conta: "3459", designacao: "IVA liquidações oficiosas", isSubAccount: true },
  { conta: "346", designacao: "Certificado de crédito fiscal a compensar" },
  { conta: "348", designacao: "Subsídios a preços" },
  { conta: "349", designacao: "Outros impostos" },
  { conta: "3491", designacao: "Financiamento saldos", isSubAccount: true },
  { conta: "3492", designacao: "Segurança social", isSubAccount: true },
  { conta: "3493", designacao: "Imposto predial", isSubAccount: true },
  { conta: "3497", designacao: "Outros impostos", isSubAccount: true },
  { conta: "35", designacao: "Entidades participantes e participadas", isGroup: true },
  { conta: "351", designacao: "Entidades participantes" },
  { conta: "352", designacao: "Entidades participadas" },
  { conta: "36", designacao: "Pessoal", isGroup: true },
  { conta: "361", designacao: "Pessoal - Remunerações" },
  { conta: "3611", designacao: "Remunerações - Órgãos sociais", isSubAccount: true },
  { conta: "3612", designacao: "Remunerações - Empregados", isSubAccount: true },
  { conta: "362", designacao: "Pessoal - Participação nos resultados" },
  { conta: "3621", designacao: "Órgãos sociais", isSubAccount: true },
  { conta: "3622", designacao: "Empregados", isSubAccount: true },
  { conta: "363", designacao: "Pessoal - Adiantamentos" },
  { conta: "3631", designacao: "Órgãos sociais", isSubAccount: true },
  { conta: "3632", designacao: "Empregados", isSubAccount: true },
  { conta: "369", designacao: "Pessoal - Outros" },
  { conta: "37", designacao: "Outros valores a receber e a pagar", isGroup: true },
  { conta: "371", designacao: "Compras de imobilizado" },
  { conta: "372", designacao: "Venda de imobilizado" },
  { conta: "373", designacao: "Proveitos a facturar" },
  { conta: "374", designacao: "Encargos a repartir por períodos futuros" },
  { conta: "3742", designacao: "Rendas", isSubAccount: true },
  { conta: "3743", designacao: "Seguros", isSubAccount: true },
  { conta: "3749", designacao: "Outros", isSubAccount: true },
  { conta: "375", designacao: "Encargos a pagar" },
  { conta: "376", designacao: "Proveitos a repartir por períodos futuros" },
  { conta: "3761", designacao: "Prémios de emissão de obrigações", isSubAccount: true },
  { conta: "3762", designacao: "Prémios de emissão de títulos de participação", isSubAccount: true },
  { conta: "3763", designacao: "Subsídios para investimento", isSubAccount: true },
  { conta: "3764", designacao: "Diferenças de câmbio favoráveis reversíveis", isSubAccount: true },
  { conta: "377", designacao: "Contas transitórias" },
  { conta: "379", designacao: "Outros valores a receber e a pagar" },
  { conta: "3791", designacao: "Contas a receber", isSubAccount: true },
  { conta: "3792", designacao: "Contas a pagar", isSubAccount: true },
  { conta: "38", designacao: "Provisões para cobrança duvidosa", isGroup: true },
  { conta: "381", designacao: "Provisões para clientes" },
  { conta: "382", designacao: "Provisões para saldos devedores de fornecedores" },
  { conta: "383", designacao: "Provisões para participantes e participadas" },
  { conta: "384", designacao: "Provisões para dívidas do pessoal" },
  { conta: "389", designacao: "Provisões para outros valores a receber" },
  { conta: "39", designacao: "Provisões para outros riscos e encargos", isGroup: true },
  { conta: "391", designacao: "Provisões para pensões" },
  { conta: "392", designacao: "Provisões para processos judiciais em curso" },
  { conta: "393", designacao: "Provisões para acidentes de trabalho" },
  { conta: "394", designacao: "Provisões para garantias dadas a clientes" },
  { conta: "399", designacao: "Provisões para outros riscos e encargos" },
];

// Class 4 — Meios Monetários
const classe4: BalanceteLine[] = [
  { conta: "4", designacao: "Meios Monetários", isGroup: true },
  { conta: "41", designacao: "Títulos negociáveis", isGroup: true },
  { conta: "411", designacao: "Acções" },
  { conta: "412", designacao: "Obrigações" },
  { conta: "413", designacao: "Títulos de dívida pública" },
  { conta: "42", designacao: "Depósitos a prazo", isGroup: true },
  { conta: "421", designacao: "Moeda nacional" },
  { conta: "422", designacao: "Moeda estrangeira" },
  { conta: "43", designacao: "Depósitos à ordem", isGroup: true },
  { conta: "431", designacao: "Moeda nacional" },
  { conta: "432", designacao: "Moeda estrangeira" },
  { conta: "44", designacao: "Outros depósitos", isGroup: true },
  { conta: "45", designacao: "Caixa", isGroup: true },
  { conta: "451", designacao: "Fundo fixo" },
  { conta: "452", designacao: "Valores para depositar" },
  { conta: "453", designacao: "Valores destinados a pagamentos específicos" },
  { conta: "48", designacao: "Conta transitória", isGroup: true },
  { conta: "481", designacao: "Banco" },
  { conta: "49", designacao: "Provisões para aplicações de tesouraria", isGroup: true },
  { conta: "491", designacao: "Títulos negociáveis" },
  { conta: "492", designacao: "Outras aplicações de tesouraria" },
];

// Class 5 — Capital e Reservas
const classe5: BalanceteLine[] = [
  { conta: "5", designacao: "Capital e Reservas", isGroup: true },
  { conta: "51", designacao: "Capital", isGroup: true },
  { conta: "511", designacao: "Capital próprio" },
  { conta: "52", designacao: "Acções/Quotas próprias", isGroup: true },
  { conta: "521", designacao: "Valor nominal" },
  { conta: "522", designacao: "Descontos" },
  { conta: "523", designacao: "Prémios" },
  { conta: "53", designacao: "Prémios de emissão", isGroup: true },
  { conta: "531", designacao: "Prémios" },
  { conta: "54", designacao: "Prestações suplementares", isGroup: true },
  { conta: "541", designacao: "Prestações suplementares" },
  { conta: "55", designacao: "Reservas Legais", isGroup: true },
  { conta: "551", designacao: "Reservas legais" },
  { conta: "552", designacao: "Fundo de investimento" },
  { conta: "553", designacao: "Fundo social" },
  { conta: "56", designacao: "Reservas de reavaliação", isGroup: true },
  { conta: "561", designacao: "Legais" },
  { conta: "562", designacao: "Autónomas" },
  { conta: "57", designacao: "Reservas com fins especiais", isGroup: true },
  { conta: "571", designacao: "Reservas" },
  { conta: "58", designacao: "Reservas livres", isGroup: true },
  { conta: "581", designacao: "Reservas livres" },
];

// Class 6 — Proveitos e Ganhos
const classe6: BalanceteLine[] = [
  { conta: "6", designacao: "Proveitos e Ganhos por Natureza", isGroup: true },
  { conta: "61", designacao: "Vendas", isGroup: true },
  { conta: "611", designacao: "Produtos acabados e intermédios" },
  { conta: "612", designacao: "Subprodutos, desperdícios, resíduos e refugos" },
  { conta: "613", designacao: "Mercadorias" },
  { conta: "614", designacao: "Embalagens de consumo" },
  { conta: "615", designacao: "Subsídios a preços" },
  { conta: "617", designacao: "Devoluções" },
  { conta: "618", designacao: "Descontos e abatimentos" },
  { conta: "62", designacao: "Prestações de Serviço", isGroup: true },
  { conta: "621", designacao: "Serviços principais" },
  { conta: "622", designacao: "Serviços secundários" },
  { conta: "628", designacao: "Descontos e abatimentos" },
  { conta: "63", designacao: "Outros proveitos operacionais", isGroup: true },
  { conta: "631", designacao: "Serviços suplementares" },
  { conta: "632", designacao: "Royalties" },
  { conta: "633", designacao: "Subsídios à exploração" },
  { conta: "634", designacao: "Subsídio a investimento" },
  { conta: "635", designacao: "IVA" },
  { conta: "638", designacao: "Outros proveitos e ganhos operacionais" },
  { conta: "64", designacao: "Variação nos inventários de prod. acabados e em curso", isGroup: true },
  { conta: "641", designacao: "Produtos e trabalhos em curso" },
  { conta: "642", designacao: "Produtos acabados" },
  { conta: "643", designacao: "Produtos intermédios" },
  { conta: "65", designacao: "Trabalhos para a própria empresa", isGroup: true },
  { conta: "651", designacao: "Para imobilizado" },
  { conta: "652", designacao: "Para encargos a repartir por exercícios futuros" },
  { conta: "66", designacao: "Proveitos e ganhos financeiros gerais", isGroup: true },
  { conta: "661", designacao: "Juros" },
  { conta: "662", designacao: "Diferenças de câmbio favoráveis" },
  { conta: "663", designacao: "Descontos de pronto pagamento obtidos" },
  { conta: "664", designacao: "Rendimentos de investimentos em imóveis" },
  { conta: "665", designacao: "Rendimentos de participações de capital" },
  { conta: "666", designacao: "Ganhos na alienação de aplicações financeiras" },
  { conta: "667", designacao: "Redução de provisões" },
  { conta: "67", designacao: "Proveitos e ganhos financeiros em subsidiárias e associadas", isGroup: true },
  { conta: "671", designacao: "Rendimento de participações de capital" },
  { conta: "68", designacao: "Outros proveitos e ganhos não operacionais", isGroup: true },
  { conta: "681", designacao: "Redução de provisões" },
  { conta: "682", designacao: "Anulação de amortizações extraordinárias" },
  { conta: "683", designacao: "Ganhos em imobilizações" },
  { conta: "684", designacao: "Ganhos em existências" },
  { conta: "685", designacao: "Recuperação de dívidas" },
  { conta: "686", designacao: "Benefícios de penalidades contratuais" },
  { conta: "688", designacao: "Descontinuidade de operações" },
  { conta: "689", designacao: "Alterações de políticas contabilísticas" },
  { conta: "6810", designacao: "Correcções relativas a exercícios anteriores" },
  { conta: "6811", designacao: "Outros ganhos e perdas não operacionais" },
  { conta: "69", designacao: "Proveitos e ganhos extraordinários", isGroup: true },
  { conta: "691", designacao: "Ganhos resultantes de catástrofes naturais" },
  { conta: "692", designacao: "Ganhos resultantes de convulsões políticas" },
  { conta: "693", designacao: "Ganhos resultantes de expropriações" },
  { conta: "694", designacao: "Ganhos resultantes de sinistros" },
  { conta: "695", designacao: "Subsídios" },
  { conta: "696", designacao: "Anulação de passivos não exigíveis" },
];

// Class 7 — Custos e Perdas
const classe7: BalanceteLine[] = [
  { conta: "7", designacao: "Custos e Perdas por Natureza", isGroup: true },
  { conta: "71", designacao: "Custo das existências vendidas", isGroup: true },
  { conta: "711", designacao: "Matérias-primas" },
  { conta: "712", designacao: "Matérias subsidiárias" },
  { conta: "713", designacao: "Materiais diversos" },
  { conta: "714", designacao: "Embalagens de consumo" },
  { conta: "715", designacao: "Outros materiais" },
  { conta: "72", designacao: "Custos com o pessoal", isGroup: true },
  { conta: "721", designacao: "Remunerações - Órgãos sociais" },
  { conta: "722", designacao: "Remunerações - Pessoal" },
  { conta: "723", designacao: "Pensões" },
  { conta: "724", designacao: "Prémios para pensões" },
  { conta: "725", designacao: "Encargos com pessoal" },
  { conta: "726", designacao: "Seguro contra acidentes de trabalho" },
  { conta: "727", designacao: "Formações" },
  { conta: "728", designacao: "Subsídios e outros custos" },
  { conta: "73", designacao: "Amortizações do exercício", isGroup: true },
  { conta: "731", designacao: "Imobilizações corpóreas" },
  { conta: "7311", designacao: "Terrenos e recursos naturais", isSubAccount: true },
  { conta: "7312", designacao: "Edifícios e outras construções", isSubAccount: true },
  { conta: "7313", designacao: "Equipamento básico", isSubAccount: true },
  { conta: "7314", designacao: "Equipamento de carga e transporte", isSubAccount: true },
  { conta: "7315", designacao: "Equipamento administrativo", isSubAccount: true },
  { conta: "7316", designacao: "Taras e vasilhame", isSubAccount: true },
  { conta: "7319", designacao: "Outras imobilizações corpóreas", isSubAccount: true },
  { conta: "732", designacao: "Imobilizações incorpóreas" },
  { conta: "7321", designacao: "Trespasses", isSubAccount: true },
  { conta: "7322", designacao: "Despesas de investigação e desenvolvimento", isSubAccount: true },
  { conta: "7323", designacao: "Propriedade industrial e outros direitos e contratos", isSubAccount: true },
  { conta: "7324", designacao: "Despesas de constituição", isSubAccount: true },
  { conta: "7329", designacao: "Outras imobilizações incorpóreas", isSubAccount: true },
  { conta: "75", designacao: "Outros custos e perdas operacionais", isGroup: true },
  { conta: "751", designacao: "Subcontratos" },
  { conta: "752", designacao: "Fornecimentos e serviços de terceiros" },
  { conta: "753", designacao: "Impostos" },
  { conta: "754", designacao: "Despesas confidenciais" },
  { conta: "755", designacao: "Quotizações" },
  { conta: "756", designacao: "Ofertas e amostras de existências" },
  { conta: "758", designacao: "Outros custos e perdas operacionais" },
  { conta: "76", designacao: "Custos e perdas financeiras gerais", isGroup: true },
  { conta: "761", designacao: "Juros" },
  { conta: "762", designacao: "Diferenças de câmbio desfavoráveis" },
  { conta: "763", designacao: "Descontos de pronto pagamento concedidos" },
  { conta: "764", designacao: "Amortizações de investimentos em imóveis" },
  { conta: "765", designacao: "Provisões para aplicações financeiras" },
  { conta: "766", designacao: "Perdas na alienação de aplicações financeiras" },
  { conta: "767", designacao: "Serviços bancários" },
  { conta: "77", designacao: "Custos e perdas financeiras em filiais e associadas", isGroup: true },
  { conta: "771", designacao: "Custos e perdas financeiras em filiais" },
  { conta: "772", designacao: "Custos e perdas financeiras em associadas" },
  { conta: "78", designacao: "Outros custos e perdas não operacionais", isGroup: true },
  { conta: "781", designacao: "Provisões do exercício" },
  { conta: "782", designacao: "Amortizações extraordinárias" },
  { conta: "783", designacao: "Perdas em imobilizações" },
  { conta: "784", designacao: "Perdas em existências" },
  { conta: "785", designacao: "Dívidas incobráveis" },
  { conta: "786", designacao: "Multas e penalidades contratuais" },
  { conta: "787", designacao: "Custos de reestruturação" },
  { conta: "788", designacao: "Descontinuidade de operações" },
  { conta: "789", designacao: "Alterações de políticas contabilísticas" },
  { conta: "7810", designacao: "Correcções relativas a exercícios anteriores" },
  { conta: "7811", designacao: "Outros custos e perdas não operacionais" },
  { conta: "79", designacao: "Custos e perdas extraordinários", isGroup: true },
  { conta: "791", designacao: "Perdas resultantes de catástrofes naturais" },
  { conta: "792", designacao: "Perdas resultantes de convulsões políticas" },
  { conta: "793", designacao: "Perdas resultantes de expropriações" },
  { conta: "794", designacao: "Perdas resultantes de sinistros" },
];

// Class 8 — Resultados
const classe8: BalanceteLine[] = [
  { conta: "8", designacao: "Resultados", isGroup: true },
  { conta: "81", designacao: "Resultados Transitados", isGroup: true },
  { conta: "811", designacao: "Resultado do ano (saldo inicial)" },
  { conta: "812", designacao: "Aplicação de resultados" },
  { conta: "813", designacao: "Correcções de erros fundamentais" },
  { conta: "814", designacao: "Efeito das alterações de políticas contabilísticas" },
  { conta: "815", designacao: "Imposto relativo a correcções de erros fundamentais" },
  { conta: "82", designacao: "Resultados operacionais", isGroup: true },
  { conta: "83", designacao: "Resultados financeiros", isGroup: true },
  { conta: "84", designacao: "Resultados de filiais e associadas", isGroup: true },
  { conta: "85", designacao: "Resultados não operacionais", isGroup: true },
  { conta: "86", designacao: "Resultados extraordinários", isGroup: true },
  { conta: "87", designacao: "Imposto sobre o rendimento", isGroup: true },
  { conta: "88", designacao: "Resultados líquidos do exercício", isGroup: true },
];

const allLines: BalanceteLine[] = [
  ...classe1, ...classe2, ...classe3, ...classe4,
  ...classe5, ...classe6, ...classe7, ...classe8,
];

export function generateCC2Template(): void {
  const wb = XLSX.utils.book_new();

  // ─── Instructions sheet ───
  const instrRows = [
    ["BALANCETE INICIAL E FINAL — MODELO CC-2 / CC-3"],
    ["Resolução Nº 1/17 — PGC (Decreto nº 82/2001, actualizado pelo Decreto Presidencial nº 180/19)"],
    [],
    ["INSTRUÇÕES DE PREENCHIMENTO"],
    [],
    ["1. Preencha os campos 'ENTIDADE' e 'PERÍODO' na folha 'Balancete'."],
    ["2. Introduza os valores em Kwanzas nas colunas 'Movim. Débito' e 'Movim. Crédito'."],
    ["3. A coluna 'Saldo do Ano Corrente' será calculada automaticamente (Débito - Crédito)."],
    ["4. A coluna 'Saldo do Ano Anterior' é para comparação com o exercício anterior."],
    ["5. As linhas a cinza (contas-mãe) são cabeçalhos — NÃO preencher directamente."],
    ["6. Preencha apenas as subcontas com valores efectivos."],
    ["7. Após preenchido, carregue este ficheiro no Portal da Entidade."],
    [],
    ["ESTRUTURA DO BALANCETE:"],
    ["  Classe 1 — Meios Fixos e Investimentos"],
    ["  Classe 2 — Existências"],
    ["  Classe 3 — Terceiros"],
    ["  Classe 4 — Meios Monetários"],
    ["  Classe 5 — Capital e Reservas"],
    ["  Classe 6 — Proveitos e Ganhos por Natureza"],
    ["  Classe 7 — Custos e Perdas por Natureza"],
    ["  Classe 8 — Resultados"],
    [],
    ["NOTA: Os valores devem ser introduzidos em Kwanzas (Kz), sem formatação."],
    ["Exemplo: 1500000.00 (e não Kz 1.500.000,00)"],
    [],
    ["O sistema irá calcular automaticamente o Balanço Patrimonial, a Demonstração de Resultados"],
    ["e os Indicadores Financeiros com base nos dados do balancete."],
  ];
  const wsInstr = XLSX.utils.aoa_to_sheet(instrRows);
  wsInstr["!cols"] = [{ wch: 90 }];
  XLSX.utils.book_append_sheet(wb, wsInstr, "Instruções");

  // ─── Balancete sheet ───
  const rows: (string | number | null)[][] = [];
  rows.push(["BALANCETE INICIAL E FINAL — ANO DE 202___"]);
  rows.push(["Valor em Kwanzas"]);
  rows.push([]);
  rows.push(["ENTIDADE:", "", "", "", ""]);
  rows.push(["PERÍODO:", "", "", "", ""]);
  rows.push([]);
  rows.push(["Conta", "Designação da Conta", "Movim. Débito", "Movim. Crédito", "Saldo do Ano Corrente", "Saldo do Ano Anterior"]);

  allLines.forEach((line) => {
    const indent = line.isSubAccount ? "  " : "";
    if (line.isGroup) {
      rows.push([line.conta, line.designacao, null, null, null, null]);
    } else {
      rows.push([line.conta, indent + line.designacao, 0, 0, 0, 0]);
    }
  });

  // Totals
  rows.push([]);
  rows.push(["", "SALDO DAS CONTAS PATRIMONIAIS", null, null, null, null]);

  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws["!cols"] = [
    { wch: 10 },
    { wch: 55 },
    { wch: 22 },
    { wch: 22 },
    { wch: 24 },
    { wch: 24 },
  ];

  XLSX.utils.book_append_sheet(wb, ws, "Balancete");

  XLSX.writeFile(wb, "Balancete_CC2_Prestacao_Contas.xlsx");
}
